title: Votroubek Facility
email: votroubekfacility@seznam.cz
phone: "+420 702 149 584"
phone_short: "702 149 584"
ico: "06526764"
dph: "DIČ: CZ8811250228"
description: Nabízím služby hodinového manžela a facility service pro Prahu a okolí.
url: "https://votroubekfacility.cz"
instagram_username: votroubek_facility
facebook_username: votroubekfacility

sass:
  style: compressed

plugins:
  - jekyll-sitemap